### ISSUE TITLE
Document [services.rss]

### ISSUE THREAD

**Issue by arif254** [gohugoio/hugoDocs#1689] opened 2022-03-18 09:12 UTC
Mention [here](https://gohugo.io/templates/rss/#the-embedded-rssxml) that this needs to be added to the config file e.g for Toml

```
[services.rss]
    limit = 8
```
Similar to #1673.

**Comment by jmooring** [comment] 2022-03-28 16:23
Duplicate of #1673

**Closed by jmooring** 2022-03-28 16:23 UTC
