### ISSUE TITLE
Group functions into categories

### ISSUE THREAD

**Issue by Wuzzy2** [gohugoio/hugoDocs#1550] opened 2021-10-26 11:11 UTC
The current function reference is very hard to read. It is all over the place and there is no structure, it's just a giant list with many very unrelated functions.
I therefore suggest to group all functions into some kind of logical hierarchy so you can find what you need faster. E.g. a category of string functions, of page functions, and so on.

I have looked at the current list of functions and have come up with a rough draft of how a potential “function tree” could look like:

----

* Control flow
    * if ... end
    * with ... end
* Data type operations
    * Shared functions
         * len
         * in
         * index
         * cond
    * Comparators
         * ge
         * gt
         * le
         * lt
         * eq
         * ne
    * Strings (without I18N)
         * string
         * Checksums / crypto
              * hmac
              * base64Encode, base64Decode
              * md5
              * sha
         * Data formats
              * jsonify
              * htmlEscape
              * htmlUnescape
              * plainify
              * markdownify
              * urlize
              * transform.Unmarshal
         * Simple conversions
              * emojify
              * highlight
              * humanize
              * singularize
              * pluralize
              * lower
              * upper
              * title
              * strings.Repeat
         * Safe strings
              * safeCSS
              * safeHTML
              * safeHTMLAttr
              * safeJS
              * safeURL
         * URL
              * absURL
              * reuURL
              * anchorize
              * querify
              * url.Parse
         * Print
              * print
              * printf
              * println
         * Changing
              * chomp
              * truncate
              * trim
              * delimit
              * split
              * substr
              * strings.TrimLeft
              * strings.TrimRight
              * strings.TrimPrefix
              * strings.TrimSuffix
         * Counting
              * countrunes
              * countwords
              * strings.Count
              * strings.RuneCount
         * Search and replace
              * hasPrefix
              * strings.HasSuffix
              * findRE
              * replace
              * replaceRE
    * Collections
         * slice
         * slicestr
         * dict
         * seq
         * reflect.IsSlice
         * reflect.IsMap
         * first
         * last
         * after
         * range
         * apply
         * sort
         * shuffle
         * symdiff
         * complement
         * intersect
         * merge
         * uniq
         * union
         * where
    * Numbers
         * int
         * float
         * Math.\* 
         * add, sub, ...
    * Date/Time
         * .AddDate
         * .Format
         * .Unix
         * now
         * time
         * time.Format
    * Scratchpads
         * .Scratch.\* 
    * I18N
         * i18n / T
         * absLangURL
         * relLangURL
         * lang.* 
         * lang.merge
* Site structure
    * Page
         * .GetPage
         * .HasMenuCurrent
         * .IsMenuCurrent
         * .Param
         * group
         * ref
         * relref
    * Partials
         * partial
         * partialCached
    * Shortcodes
         * .Get
    * Site
         * site
* Parameters / Settings
    * isset
    * echoParam
    * default
* Render
    * .Render
    * .RenderString
* Resources
    * Files / Directories
         * fileExists
         * templates.Exists
         * readFile
         * readDir
         * path.\* 
         * os.Stat
    * Images
         * images.\* 
* System
    * getenv
    * hugo
* Debug
    * errorf
    * warnf

**Comment by jmooring** [comment] 2023-09-30 20:57
Duplicate of #53

**Closed by jmooring** 2023-09-30 20:57 UTC
Labels: Design
