### ISSUE TITLE
mod and modBool does not show up in search

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#184] opened 2017-09-11 06:52 UTC
Not sure how they vanished.

**Comment by digitalcraftsman** [comment] 2017-09-11 07:06
They aren't. As part of the `math` namespace they have been moved into the same-named [subsection](https://gohugo.io/functions/math/). I guess, all math related functions have been moved into a single file because documenting every function on it's own seemed a bit odd.

**Comment by bep** [comment] 2017-09-11 07:13
OK; that is fine -- but I tried to search for it, and neither "mod", "modBool" or "Modulus" give any match.

**Comment by digitalcraftsman** [comment] 2017-09-11 07:18
Tried it as well. The search should be adjusted to take the content into account as well (at least here).

**Comment by kaushalmodi** [comment] 2018-03-16 18:07
Should this issue be closed? Because it seems to be the same issue as https://github.com/gohugoio/gohugoioTheme/issues/63.

**Comment by jmooring** [comment] 2022-11-13 04:42
`modbool` shows up in search, but `mod` and `modulus` do not. 

`math mod` will show the mod function.

I don't know where to adjust this.

**Comment by jmooring** [comment] 2023-08-06 17:06
Closing as duplicate of #2081

**Closed by jmooring** 2023-08-06 17:06 UTC
Labels: Important
