### ISSUE TITLE
Instagram embeds no longer work

### ISSUE THREAD

**Issue by willduncanphoto** [gohugoio/hugoDocs#1166] opened 2020-07-06 08:57 UTC
Due to legal issues with copyright violations, Instagram appears to have killed embedded content on external sites.

Would you all like me to add some context to that in the documentation? It may throw new users off who don't know.

I'm not sure if they plan to even restore it.  But for the time being, you can't embed an IG image using shortcode.  You just get a rendered box with no image and have to click it and be taken to Instagram.

Figured I could add a preface or section in the docs with an explanation of why that is.

**Comment by jmooring** [comment] 2020-07-10 14:56
> you can't embed an IG image using shortcode

I am unable to reproduce this behavior. This works fine:

```md
{{< instagram BWNjjyYFxVx >}}
```

I am aware of [McGucken v. Newsweek](https://law.justia.com/cases/federal/district-courts/new-york/nysdce/1:2019cv09617/524753/35/). It will be in the courts for a very long time. 

Please test again. If you continue to have problems please create a topic on the [discussion forum](https://discourse.gohugo.io).

**Comment by coliff** [comment] 2020-07-16 05:09
Instagram embeds are working fine - I suggest we close this issue.

**Closed** 2020-07-16 10:04 UTC
