### ISSUE TITLE
Use of undocumented API in example code

### ISSUE THREAD

**Issue by septs** [gohugoio/hugoDocs#1995] opened 2023-03-12 02:04 UTC
Define:

https://github.com/gohugoio/hugo/blob/84201e8d5d319399a868e64d20d7a40e5aae2023/resources/page/page.go#L324-L326

Using:

https://github.com/gohugoio/hugoDocs/blob/142f5da818aec50144dd837e18054448d321cc29/content/en/content-management/diagrams.md?plain=1#L54

Search:

https://github.com/search?q=repo%3Agohugoio%2FhugoDocs+.Store+language%3AMarkdown&type=code&l=Markdown

see https://github.com/gohugoio/hugo/issues/10817

**Comment by jmooring** [comment] 2023-03-12 02:40
Duplicate of #1668.

**Closed by jmooring** 2023-03-12 02:40 UTC
